### ISSUE TITLE
.xml not downloading anymore

### ISSUE THREAD

**Issue by Rougoku** [DigitalFlow/Pokemon-Team-Builder#3]
Hello ! I used this program for a long time, while I was playing 6G OU, but I took a break and I saw that the program contained some errors. I downloaded the most recent version.

The .xml don't download anymore, which mean that : 

- It's not up to date with the new 7G pokemon.
- You can't make a team for a tier if you didn't download the .xml before.

Thanks in advance.

**Comment by DigitalFlow** [comment]
Hey there,

It's great to hear that you used it a lot and liked it, I appreciate it a lot.

My data source is not yet up to date with Gen7, so unfortunately I can not yet update it.
I'm eagerly waiting as well. As soon as the data source is up to date, I'll integrate it as soon as possible.

I'll check on why the xml does not download anymore and publish a fix.

Thanks for creating this issue.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Hey @Rougoku,

unfortunately my provider for the data went offline and there is no Gen 7 data available from this source.

As I used this tool a lot myself and don't want to go without it, I decided to create a successor project.
The goal was to provide the same team building capabilities, while being able to be executed on all devices and not relying on an uncertain data source.

It is still in build, but you can already view stats from Smogon. 
It is basically a HTML page using react, where you can import stat files, that were downloaded from Smogon previously.
I'm in the progress of adding the team builder and hope to finish it anytime soon. You can find the new project [here](https://github.com/DigitalFlow/Smogon-Team-Assistance).

Kind Regards,
Florian
